name: lab testes
on:
  workflow_dispatch:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        with:
          clean: true

      - name: Check out repository templates-pipeline
        uses: actions/checkout@v4
        with:
          repository: 'lab-pessoal/templates-pipeline'
          ref: 'refs/heads/main'
          token: ${{ secrets.GH_TOKEN }}
          path: 'templates-pipeline'

      - name: Build NPM
        uses: ./templates-pipeline/.github/workflows/actions/node/build

      - name: Run application
        run: |
          npm start &
          for i in {1..30}; do
            curl -sf http://localhost:3000/health && break
            sleep 2
          done

      - name: k6
        env:
          API_URL: http://localhost:3000
        uses: ./templates-pipeline/.github/workflows/actions/k6